# Generated by Django 5.2 on 2025-07-13 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="seat",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="bookings.seat"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together={("user", "seat")},
        ),
    ]
